//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KotaeteMVC.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AnswerStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnswerStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KotaeteMVC.App_GlobalResources.AnswerStrings", typeof(AnswerStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already answered this question!.
        /// </summary>
        public static string AlreadyAnswered {
            get {
                return ResourceManager.GetString("AlreadyAnswered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string AnswerFieldName {
            get {
                return ResourceManager.GetString("AnswerFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The max length for an answer is 1400 characters.
        /// </summary>
        public static string AnswerMaxLengthError {
            get {
                return ResourceManager.GetString("AnswerMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;s answers.
        /// </summary>
        public static string Answers {
            get {
                return ResourceManager.GetString("Answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asked.
        /// </summary>
        public static string AskedHeader {
            get {
                return ResourceManager.GetString("AskedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question you are trying to reply to was deleted.
        /// </summary>
        public static string DeletedQuestionDetailWarning {
            get {
                return ResourceManager.GetString("DeletedQuestionDetailWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your answer cannot be empty.
        /// </summary>
        public static string EmptyAnswerError {
            get {
                return ResourceManager.GetString("EmptyAnswerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error posting your answer.
        /// </summary>
        public static string ErrorAnswer {
            get {
                return ResourceManager.GetString("ErrorAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;s liked answers.
        /// </summary>
        public static string Likes {
            get {
                return ResourceManager.GetString("Likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user hasn&apos;t replied to any question yet.
        /// </summary>
        public static string NoAnswers {
            get {
                return ResourceManager.GetString("NoAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No answers.
        /// </summary>
        public static string NoAnswersTitle {
            get {
                return ResourceManager.GetString("NoAnswersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user has not liked any answer yet.
        /// </summary>
        public static string NoLikes {
            get {
                return ResourceManager.GetString("NoLikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No likes.
        /// </summary>
        public static string NoLikesTitle {
            get {
                return ResourceManager.GetString("NoLikesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user has not asked any questions yet.
        /// </summary>
        public static string NoQuestions {
            get {
                return ResourceManager.GetString("NoQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No questions.
        /// </summary>
        public static string NoQuestionsTitle {
            get {
                return ResourceManager.GetString("NoQuestionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question you are trying to reply to cannot be found.
        /// </summary>
        public static string QuestionDetailNotFound {
            get {
                return ResourceManager.GetString("QuestionDetailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This question was not asked to you!.
        /// </summary>
        public static string QuestionDetailNotToCurrentUser {
            get {
                return ResourceManager.GetString("QuestionDetailNotToCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;s questions.
        /// </summary>
        public static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to replied.
        /// </summary>
        public static string RepliedHeader {
            get {
                return ResourceManager.GetString("RepliedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your answer was posted.
        /// </summary>
        public static string SuccessAnswer {
            get {
                return ResourceManager.GetString("SuccessAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFoundErrorHeader {
            get {
                return ResourceManager.GetString("UserNotFoundErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user does not exist.
        /// </summary>
        public static string UserNotFoundErrorMessage {
            get {
                return ResourceManager.GetString("UserNotFoundErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your answer.
        /// </summary>
        public static string YourAnswer {
            get {
                return ResourceManager.GetString("YourAnswer", resourceCulture);
            }
        }
    }
}
