//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainGlobal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainGlobal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MainGlobal", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        internal static string ClickToGoBackLink {
            get {
                return ResourceManager.GetString("ClickToGoBackLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click.
        /// </summary>
        internal static string ClickToGoBackMessageFirst {
            get {
                return ResourceManager.GetString("ClickToGoBackMessageFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to go back..
        /// </summary>
        internal static string ClickToGoBackMessageSecond {
            get {
                return ResourceManager.GetString("ClickToGoBackMessageSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error contacting the database.
        /// </summary>
        internal static string DatabaseError {
            get {
                return ResourceManager.GetString("DatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorHeader {
            get {
                return ResourceManager.GetString("ErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your question to .
        /// </summary>
        internal static string QuestionAskedSuccessfullyFirstHalf {
            get {
                return ResourceManager.GetString("QuestionAskedSuccessfullyFirstHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  was successfully posted.
        /// </summary>
        internal static string QuestionAskedSuccessfullySecondHalf {
            get {
                return ResourceManager.GetString("QuestionAskedSuccessfullySecondHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question cannot be empty.
        /// </summary>
        internal static string QuestionContentMissing {
            get {
                return ResourceManager.GetString("QuestionContentMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  was not found!.
        /// </summary>
        internal static string UserNotFoundErrorHeading {
            get {
                return ResourceManager.GetString("UserNotFoundErrorHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user you are trying to see does not exist.
        /// </summary>
        internal static string UserNotFoundErrorMessage {
            get {
                return ResourceManager.GetString("UserNotFoundErrorMessage", resourceCulture);
            }
        }
    }
}
