//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UsersStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UsersStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.UsersStrings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow.
        /// </summary>
        internal static string FollowButton {
            get {
                return ResourceManager.GetString("FollowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followers.
        /// </summary>
        internal static string FollowerPluralLabel {
            get {
                return ResourceManager.GetString("FollowerPluralLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follower.
        /// </summary>
        internal static string FollowerSingularLabel {
            get {
                return ResourceManager.GetString("FollowerSingularLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error following or unfollowing this user.
        /// </summary>
        internal static string FollowingError {
            get {
                return ResourceManager.GetString("FollowingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following.
        /// </summary>
        internal static string FollowingLabel {
            get {
                return ResourceManager.GetString("FollowingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now following .
        /// </summary>
        internal static string FollowingSuccess {
            get {
                return ResourceManager.GetString("FollowingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follows you.
        /// </summary>
        internal static string FollowsYou {
            get {
                return ResourceManager.GetString("FollowsYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likes.
        /// </summary>
        internal static string LikesPluralLabel {
            get {
                return ResourceManager.GetString("LikesPluralLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like.
        /// </summary>
        internal static string LikesSingularLabel {
            get {
                return ResourceManager.GetString("LikesSingularLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string LocationLabel {
            get {
                return ResourceManager.GetString("LocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user has no followers yet. You could try following them!.
        /// </summary>
        internal static string NoFollowers {
            get {
                return ResourceManager.GetString("NoFollowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No followers.
        /// </summary>
        internal static string NoFollowersTitle {
            get {
                return ResourceManager.GetString("NoFollowersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is not following anyone yet.
        /// </summary>
        internal static string NoFollowing {
            get {
                return ResourceManager.GetString("NoFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not following anyone.
        /// </summary>
        internal static string NoFollowingTitle {
            get {
                return ResourceManager.GetString("NoFollowingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not following you.
        /// </summary>
        internal static string NotFollowingYou {
            get {
                return ResourceManager.GetString("NotFollowingYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s you.
        /// </summary>
        internal static string OwnProfile {
            get {
                return ResourceManager.GetString("OwnProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        internal static string QuestionsPluralLabel {
            get {
                return ResourceManager.GetString("QuestionsPluralLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string QuestionsSingularLabel {
            get {
                return ResourceManager.GetString("QuestionsSingularLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replies.
        /// </summary>
        internal static string ReplyPluralLabel {
            get {
                return ResourceManager.GetString("ReplyPluralLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        internal static string ReplySingularLabel {
            get {
                return ResourceManager.GetString("ReplySingularLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfollow.
        /// </summary>
        internal static string UnfollowButton {
            get {
                return ResourceManager.GetString("UnfollowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not following .
        /// </summary>
        internal static string UnfollowingSuccessFst {
            get {
                return ResourceManager.GetString("UnfollowingSuccessFst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  anymore.
        /// </summary>
        internal static string UnfollowingSuccessLst {
            get {
                return ResourceManager.GetString("UnfollowingSuccessLst", resourceCulture);
            }
        }
    }
}
